[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Optimize Node.js memory usage for large builds
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Enable build caching
  NPM_FLAGS = "--prefer-offline --no-audit --progress=false"

# Cache-First static assets with long-term caching
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Cache images and fonts for better performance
[[headers]]
  for = "*.{woff,woff2,ttf,eot,otf}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.{png,jpg,jpeg,webp,gif,svg,ico}"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    X-Content-Type-Options = "nosniff"

# Security and performance headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https://cdn.shopify.com https://*.myshopify.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://*.myshopify.com https://api.yourlist.com;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    X-DNS-Prefetch-Control = "on"
    # Preconnect to Shopify domains for faster loading
    Link = "</fonts/Bangers.woff2>; rel=preload; as=font; type=font/woff2; crossorigin, <https://cdn.shopify.com>; rel=preconnect; crossorigin"

# Specific caching for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"

# Redirects for SEO optimization
[[redirects]]
  from = "/shop.html"
  to = "/shop"
  status = 301

[[redirects]]
  from = "/contact.html"
  to = "/contact"
  status = 301

# Trailing slash normalization
[[redirects]]
  from = "/shop/"
  to = "/shop"
  status = 301

[[redirects]]
  from = "/contact/"
  to = "/contact"
  status = 301